modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "yep"
version = "${version}"
displayName = "Yep"
logoFile = "icon.png"
authors = "foooooooooooo, unilock"
description = '''
Send death / advancement messages to VelocityDiscord over the plugin channel "velocity:yep"
'''

[[dependencies.yep]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.yep]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "SERVER"
